users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views


urlpatterns = [
	#登录页面
	#url(r'^login/$', login, {'template_name': 'users/login.html'}, name = 'login'),
	url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name="login"),
	url(r'^logout/$', views.logout_view, name="logout"),
	#url(r'^register/$', views.register, name="register"),
]

working_log/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('working_logs.urls', 'working_logs'), namespace='working_logs')),
    re_path(r'^users/', include(('users.urls', 'users'), namespace='users'))
]

working_logs/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'projects/(?P<pindex>\d*)/$', views.projects, name='projects'),
    re_path(r'results/(?P<projects_name>\w*)/(?P<pindex>\d+)/$', views.results, name='results'),
    re_path(r'^project/(?P<project_id>\d+)/$', views.project, name ='project'),
    re_path(r'^review/(?P<project_id>\d+)/$', views.review, name ='review'),
    re_path(r'^new_project/$', views.new_project, name = 'new_project'),
    re_path(r'^new_opinion/(?P<project_id>\d+)/$', views.new_opinion, name='new_opinion'),
    re_path(r'^edit_opinion/(?P<opinion_id>\d+)/$', views.edit_opinion, name='edit_opinion'),
    re_path(r'^delete_project/(?P<project_id>\d+)/$', views.delete_project, name='delete_project'),
    re_path(r'^delete_opinion/(?P<opinion_id>\d+)/$', views.delete_opinion, name='delete_opinion'),
    re_path(r'^search_project/', views.search, name='search'),
    re_path(r'^add_img/(?P<project_id>\d+)/$', views.img_upload, name='add_img'),
    re_path(r'^show_img/(?P<project_id>\d+)/$', views.img_show, name='show_img'),
    re_path(r'^delete_img/(?P<img_id>\d+)/$', views.delete_img, name='delete_img'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models

# Create your models here.

working_logs/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    """施工项目申请单号"""
    text = models.CharField(max_length=200)
    date_added  = models.DateField()
    time_added = models.TimeField(auto_now_add=True)
    STATE_CHOICES = (
        ('pending', 'pending'),
        ('reviewed', 'reviewed'),
    )
    state = models.CharField(max_length=15, choices=STATE_CHOICES, default='pending')

    def __str__(self):
        return self.text
    
    class Meta:
        permissions = (("can_approve_or_reject_project", "Can approve or reject project"),)


class Opinion(models.Model):
    """审批意见"""
    project = models.ForeignKey(Project, on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateField()
    time_added = models.TimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural  = 'Opinions'

    def __str__(self):
        return self.text[:50] + '...'


class Img(models.Model):
    """添加图片"""
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    img_url = models.FileField(upload_to='photos/',blank=True,null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    #name = models.CharField(max_length=20)

    class Meta:
        verbose_name_plural = 'Imgs'
    
    def __str__(self):
        return str(self.date_added)

working_logs/forms.py
from django import forms
from .models import Project, Opinion, Img
from django.forms import SelectDateWidget
from datetime import datetime

y = datetime.now().strftime('%Y')
Y = int(y)
YEARS = [(Y+i) for i in range(-5, 5)]
MONTHS = {
    1:1, 2:2, 3:3, 4:4,
    5:5, 6:6, 7:7, 8:8,
    9:9, 10:10, 11:11, 12:12
}
d = [i for i in range(1, 32)]

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['text', 'date_added']
        labels = {'text': '项目名称  ', 'date_added': '添加时间'}
        widgets = {'date_added': SelectDateWidget(years=YEARS, months=MONTHS)}

class OpinionForm(forms.ModelForm):
    class Meta:
        model = Opinion
        fields = ['text', 'date_added']
        labels = {'text': '', 'date_added': '添加时间'}
        widgets = {'date_added': SelectDateWidget(years=YEARS, months=MONTHS),
         'text': forms.Textarea(attrs={'cols': 80})
        }

class ImgForm(forms.ModelForm):
    class Meta:
        model = Img
        fields = ['img_url']
        labels = {'img_url':''}
        widgets = {'img_url':forms.ClearableFileInput(attrs={'multiple': True})}


class ReviewForm(forms.Form):
    APPROVAL_CHOICES = (
        ('approve', 'Approve this project'),
        ('pending', 'Pending this project'),
    )
    approval = forms.ChoiceField(choices=APPROVAL_CHOICES, widget=forms.RadioSelect)

working_logs/views.py
from django.shortcuts import render
from .models import Project, Opinion, Img
from .forms import ProjectForm, OpinionForm, ImgForm, ReviewForm
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator
from django.db.models import Count


PAGE_ITEMS = 20
#PAGES = Paginator(Project.objects.all(), 20).num_pages
# Create your views here.
def index(request):
    """工作笔记主页"""
    if request.method != "POST":
        return render(request, 'working_logs/index.html')
    else:
        projects_name = request.POST['project_name']
        return HttpResponseRedirect(reverse('working_logs:results', kwargs={'projects_name': projects_name, 'pindex': 1}))

@login_required 
def results(request, projects_name, pindex):
    if projects_name != '':
        if projects_name in ('reviewed', 'pending'):
            projects = Project.objects.filter(state=projects_name)
        else:
            projects = Project.objects.filter(text__contains=projects_name)
        if len(projects) == 0:
             return HttpResponseRedirect(reverse("working_logs:index"))
        paginator = Paginator(projects, 20)
        if pindex == "":
            pindex = 1
        else:
            int(pindex)
        page = paginator.page(pindex)
        context = {'projects_name': projects_name, 'page': page}
        return render(request, 'working_logs/results.html', context)
    else:
        return HttpResponseRedirect(reverse("working_logs:index"))
    

@login_required
def projects(request, pindex):
    """显示所有工程项目"""
    projects = Project.objects.order_by('date_added') 
    paginator = Paginator(projects, 20)
    if pindex == "":
        pindex = 1
    else:
        int(pindex)
    page = paginator.page(pindex)
    context = {'page': page}
    return render(request, 'working_logs/projects.html', context)
        


@login_required
def project(request, project_id):
    """显示工程项目的明细"""
    project = Project.objects.get(id=project_id)
    opinions = project.opinion_set.order_by('date_added')
    
    imgs = project.img_set.all()
    img_exist = False
    if len(imgs) > 0:
        img_exist = True
    context = {'project': project, 'opinions':opinions, 'img_exist': img_exist}
    return render(request, 'working_logs/project.html', context)
   

@permission_required('working_logs.can_approve_or_reject_project',login_url='/users/login')
def review(request, project_id):
    project = Project.objects.get(id=project_id)
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['approval'] == 'approve':
                project.state = 'reviewed'
            else:
                project.state = 'pending'
            project.save()
            return HttpResponseRedirect(reverse("working_logs:project", kwargs={'project_id': project.id}))          
    else:
        form = ReviewForm()
    context = {'project': project, 'form': form}
    return render(request, 'working_logs/review.html', context)


@login_required
def new_project(request):
    """添加新项目"""
    num_list = list(Project.objects.aggregate(Count('id')).values())
    #print(num_list[0])
    page_num = (num_list[0] + 1) // PAGE_ITEMS  
    odds = (num_list[0] + 1) % PAGE_ITEMS
    fpnum = 1
    if page_num == 0:
        fpnum = 1
    else:
        fpnum = int(page_num) + 1
        
    if request.method != 'POST':
        form = ProjectForm()
    else:
        form = ProjectForm(request.POST)
        if form.is_valid():
            new_proj = form.save(commit=False)
            new_proj.state = 'pending'
            new_proj.save()
            return HttpResponseRedirect(reverse("working_logs:projects", kwargs={'pindex': fpnum}))
    context = {'form': form}
    return render(request, 'working_logs/new_project.html', context)

@login_required
def new_opinion(request, project_id):
    """添加意见"""
    project = Project.objects.get(id=project_id)
    if request.method != "POST":
        form = OpinionForm()
    else:
        form = OpinionForm(data=request.POST)
        if form.is_valid():
            new_opinion = form.save(commit=False)
            new_opinion.project = project
            new_opinion.save()
            return HttpResponseRedirect(reverse('working_logs:project', args=[project_id]))
    context = {'project': project, 'form': form}
    return render(request, 'working_logs/new_opinion.html', context)

@login_required
def edit_opinion(request, opinion_id):
    """编辑意见"""
    opinion = Opinion.objects.get(id=opinion_id)
    project = opinion.project
    if request.method != "POST":
        form = OpinionForm(instance=opinion)
    else:
        form = OpinionForm(instance=opinion, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('working_logs:project', args=[project.id]))
    context = {'project': project, 'opinion': opinion, 'form': form}
    return render(request, 'working_logs/edit_opinion.html', context)


@login_required
def delete_project(request, project_id):
    project = Project.objects.get(id=project_id)
    project.delete()
    return HttpResponseRedirect(reverse('working_logs:projects', kwargs={'pindex': 1}))


@login_required
def delete_opinion(request, opinion_id):
    opinion = Opinion.objects.get(id=opinion_id)
    project = opinion.project
    opinion.delete()
    return HttpResponseRedirect(reverse('working_logs:project', args=[project.id]))


@login_required
def search(request):
    project_name = request.POST.get('project')
    if request.method != "POST":
        HttpResponseRedirect(reverse('working_logs:index'))
    else:
        try:
            project = Project.objects.get(text=project_name)
        except:
            return HttpResponseRedirect(reverse('working_logs:projects'))
       
        return HttpResponseRedirect(reverse('working_logs:project', args=[project.id]))


def img_upload(request, project_id):
    """
    图片上传
    """
    project = Project.objects.get(id=project_id)
    if request.method != "POST":
        form = ImgForm() 
    else:
        #print('request is', request.POST, request.FILES)
        files = request.FILES.getlist('img_url')
        if len(files) == 0:
            return HttpResponseRedirect(reverse('working_logs:add_img', args=[project.id]))
    
        for i in range(len(files)):
            form = ImgForm(files={'img_url': files[i]})
            #print(vars(form))
            if form.is_valid():
                new_img = form.save(commit=False)
                new_img.project = project
                print(new_img.img_url)
                new_img.save()           
                
        return HttpResponseRedirect(reverse('working_logs:show_img', args=[project.id]))  
        
    context = {'project': project, 'form': form}
    return render(request, 'working_logs/img_upload.html', context)


def img_show(request, project_id):
    """
    图片显示
    """
    project = Project.objects.get(id=project_id)
    imgs = project.img_set.order_by('date_added')
    context = {'project':project, 'imgs':imgs}
    return render(request, 'working_logs/img_show.html', context)
  

def delete_img(request, img_id):
    img = Img.objects.get(id=img_id)
    project = img.project
    img.delete()
    return HttpResponseRedirect(reverse('working_logs:show_img', args=[project.id]))

'''
def img_upload(request, project_id):
    project = Project.objects.get(id=project_id)
    if request.method == 'POST':
        files = request.FILES.getlist('img')
        print(request.FILES)
        print(files)
        
        for f in files:
            print(type(f))
            form = ImgForm(request.POST or None, f or None)
            if form.is_valid():
                new_img = form.save(commit=False)
                new_img.project = project    
                if new_img.img_url:
                    new_img.save()
                else:
                    return HttpResponseRedirect(reverse('working_logs:add_img', args=[project.id]))
        return HttpResponseRedirect(reverse('working_logs:show_img', args=[project.id]))
    context = {'project': project}
    return render(request, 'working_logs/img_upload.html', context)'''

working_logs/templates/working_logs/base.html
{% load bootstrap3 %}
<html lang="ch">
  <head>
      <meta charset='utf-8'>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>working Log</title>
      <script src="http://upcdn.b0.upaiyun.com/libs/jquery/jquery-2.0.2.min.js">
      </script>
      {% bootstrap_javascript %}
      {% bootstrap_css %}  
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'working_logs:index' %}">working Log</a>
        </div>
        

    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'working_logs:projects' '1' %}">Projects <span class="sr-only">(current)</span></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{user.username}}.</a></li>
              <li><a href="{% url 'users:logout'%}">log out</a></li>
            {% else %} 
              <li><a href="{%url 'users:login' %}">log in</a></li>
            {% endif %}
          </ul>
          <form class="navbar-form navbar-right" class="form" action="{% url 'working_logs:index' %}" method="POST">
            {% csrf_token%}
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search" name="project_name">
            </div>
            <button type="submit" class="btn btn-default">项目查询</button>
          </form>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
      <div class="container">
        <div class="page-header">
          {% block header %}{% endblock header %}
        </div>
        <div>
          {% block content %}{% endblock content %}
        </div>
      </div>
</body>

working_logs/templates/working_logs/edit_opinion.html
{% extends "working_logs/base.html" %}
<head>{{form.media}}</head>
{% block content %}
  <p><a href="{% url 'working_logs:project' project.id %}">{{project}}</a></p>

  <p>Edit opinion</p>
    <form action="{% url 'working_logs:edit_opinion' opinion.id %}" method="post">
      {% csrf_token %}
      {{form.as_p}}
        <button name="submit">save changes</button>
    </form>
{% endblock content%}

working_logs/templates/working_logs/img_show.html
{% extends "working_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>项目图片</h2>
{% endblock header %}

{% block content %}
<head>{{form.media}}</head>
    

  <div class="panel panel-default">
    <div class="panel-heading">
    {% for img in imgs %}
      <p><img class="img-responsive" alt="响应式图像" src="{{ img.img_url.url }}">
        &ensp; &ensp; &ensp; &ensp; &ensp; <a style=" color:rgb(219, 27, 27); font-size:20px;" href="{% url 'working_logs:delete_img' img.id%}">delete</a></p>
      
    {% empty %}
      还没有图片被添加！
    {% endfor %}
    </div>
  </div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3><a href="{% url 'working_logs:add_img' project.id %}">继续添加</a></h3>
    </div>
</div>

{% endblock content %}

working_logs/templates/working_logs/img_upload.html
{% extends "working_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>添加图片</h2>
{% endblock header %}

{% block content %}
<head>{{form.media}}</head>
  <p>Add picture:</p>
    
    <form action="{% url 'working_logs:add_img' project.id %}" method="POST" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button name="submit" class="btn btn-primary">add picture</button>
        {% endbuttons %}
    </form>
{% endblock content %}

working_logs/templates/working_logs/index.html
{% extends "working_logs/base.html" %}

{% block header %}
  <div class='jumbotron'>
    <h3>Track your working.</h3>
  </div>
{% endblock header %}

{% block content %}
  <p>Working Log helps you keep track of your working!</p>
{% endblock content %}

working_logs/templates/working_logs/model.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'working_logs:index' %}">working Log</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'working_logs:projects' %}">Projects <span class="sr-only">(current)</span></a></li>
      </ul>
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="project">
        </div>
        <button type="submit" class="btn btn-default">项目查询</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

working_logs/templates/working_logs/new_opinion.html
{% extends "working_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2><a href="{% url 'working_logs:project' project.id %}">{{project}}</a></h2>
{% endblock header %}
<head>
    {{form.media}}
</head>

{% block content %}
  <p>
    Add a new opinion:
  </p>
      <form action="{% url 'working_logs:new_opinion' project.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button name="submit" class="btn btn-primary">add opinion</button>
        {% endbuttons %}
      </form>
  
{% endblock content %}

working_logs/templates/working_logs/new_project.html
{% extends "working_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>添加一个新项目</h2>
{% endblock header %}

{% block content %}
<head>{{form.media}}</head>
  <p>Add a new project:</p>
    
    <form action="{% url 'working_logs:new_project' %}" method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button name="submit" class="btn btn-primary">add project</button>
        {% endbuttons %}
    </form>

{% endblock content %}

working_logs/templates/working_logs/project.html
{% extends 'working_logs/base.html' %}

{% block header %}
  <h4>工程项目:{{project}}</h4>
  <h4>添加日期:{{project.date_added}}-{{project.time_added}}</h4>
  
{% endblock header %}

{% block content %}
  <p>
    <a href="{% url 'working_logs:new_opinion' project.id %}">add new opinion</a>
  </p>
  

  {% for opinion in opinions %}
  <ul>
    <div class="panel panel-default">
      <div class="panel-heading">
          <p>{{opinion.text|linebreaks}}</p>
          <p>{{opinion.date_added}}-{{opinion.time_added}}</p>
          <p>
              <a href="{% url 'working_logs:edit_opinion' opinion.id %}">edit opinion</a>-
              <a href="{% url 'working_logs:delete_opinion' opinion.id %}">delete opinion</a>
          </p>
    
      </div>
    </div>
  {% empty %}
    还没有意见被添加！
  {% endfor %}
  </ul>

  <br>

 
  {% if img_exist %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <p><a href="{% url 'working_logs:show_img' project.id %}">查看图片</a></p>
    </div>
  </div>
  {% elif not img_exist %}
    还没有图片被添加！
  {% endif %}
    
  <div class="panel panel-default">
    <div class="panel-heading">
      <p><a href="{% url 'working_logs:add_img' project.id %}">添加图片</a></p>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4>项目状态：{{project.state}}</h4>
      <p><a href="{% url 'working_logs:review' project.id %}">审查</a></p>
    </div>
  </div>
  
  
{% endblock content %}

working_logs/templates/working_logs/projects.html
{% extends "working_logs/base.html" %}

{% block header %}
  <h2>Projects</h2>
{% endblock header %}

{% block content %}
  <p> 
    <script language="javascript"> 
      function delcfm() { 
          if (!confirm("确认要删除？")) { 
              window.event.returnValue = false; 
          } 
      } 
    </script>
  </p> 
  <div class="container">
    <div class="btn-group pull-right row">
      <div class="col-xs-4 col-md-4">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          筛选 <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><a href="{% url 'working_logs:results' 'reviewed' 1 %}">已审阅</a></li>
          <li><a href="{% url 'working_logs:results' 'pending' 1 %}">处理中</a></li>
        </ul>
      </div>
    </div>
  </div>




  <ul>
    {% for project in page %}
      
          <div class="container">
            <div class="row">
              <tr class="success">
              <div class="col-md-4 col-xs-6">
              {% if project.state == "reviewed" %}
                <div class="list-group">
                  <a href="{% url 'working_logs:project' project.id %}" class="list-group-item list-group-item-success">
                  <h5 class="list-group-item-heading">{{project}}</h5>
                  <small><p class="list-group-item-text">{{project.date_added}}</p></small>
                  </a>
                </div>
              {% else %}
                <div class="list-group">
                  <a href="{% url 'working_logs:project' project.id %}" class="list-group-item">
                  <h5 class="list-group-item-heading">{{project}}</h5>
                  <small><p class="list-group-item-text">{{project.date_added}}</p></small>
                  </a>
                </div>
              {% endif %}
              </div>
              </tr>
            
              <div class="col-md-2 col-md-offset-1 col-xs-2">
                <button type="button" class="btn btn-default"><a onclick=delcfm() href="{% url 'working_logs:delete_project' project.id%}">删除</a></button>   
              </div>

              <div class="col-md-2 col-xs-2">
                <button type="button" class="btn btn-default"><a href="{% url 'working_logs:review' project.id%}">审查</a></button>   
              </div>

            </div>            
          </div>
    {% empty %}
      <li>还没有项目被添加</li>
    {% endfor %}
  </ul>
    
    <h4><a href="{% url 'working_logs:new_project' %}">Add a new project</a></h4>


  <nav aria-label="Page navigation">
    <ul class="pagination">
      {% if page.has_previous %}
          <li>
            <a href="{% url 'working_logs:projects' page.previous_page_number %}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
      {% endif %}

      {% for num in page.paginator.page_range %}
          {% if num == page.number %}
            <li class='active'><a href="#">{{num}}</a></li>
          {% else %}
            <li><a href="{% url 'working_logs:projects' num %}">{{num}}</a></li>
          {% endif %}
      {% endfor %}

      {% if page.has_next %}
          <li>
            <a href="{% url 'working_logs:projects' page.next_page_number %}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
      {% endif %}
    </ul>
  </nav>
  {% endblock content %}

working_logs/templates/working_logs/results.html
{% extends "working_logs/base.html" %}

{% block header %}
  <h2>Projects</h2>
{% endblock header %}

{% block content %}

<p> 
  <script language="javascript"> 
    function delcfm() { 
        if (!confirm("确认要删除？")) { 
            window.event.returnValue = false; 
        } 
    } 
  </script>
</p> 

<div class="container">
  <div class="btn-group pull-right row">
    <div class="col-xs-4 col-md-4">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        筛选 <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><a href="{% url 'working_logs:results' 'reviewed' 1 %}">已审阅</a></li>
        <li><a href="{% url 'working_logs:results' 'pending' 1 %}">处理中</a></li>
      </ul>
    </div>
  </div>
</div>



<ul>
  {% for project in page %}
    
        <div class="container">
          <div class="row">
            <tr class="success">
            <div class="col-md-4 col-xs-6">
            {% if project.state == "reviewed" %}
              <div class="list-group">
                <a href="{% url 'working_logs:project' project.id %}" class="list-group-item list-group-item-success">
                <h5 class="list-group-item-heading">{{project}}</h5>
                <small><p class="list-group-item-text">{{project.date_added}}</p></small>
                </a>
              </div>
            {% else %}
              <div class="list-group">
                <a href="{% url 'working_logs:project' project.id %}" class="list-group-item">
                <h5 class="list-group-item-heading">{{project}}</h5>
                <small><p class="list-group-item-text">{{project.date_added}}</p></small>
                </a>
              </div>
            {% endif %}
            </div>
            </tr>
          
            <div class="col-md-2 col-xs-2 col-md-offset-1">
              <button type="button" class="btn btn-default"><a onclick=delcfm() href="{% url 'working_logs:delete_project' project.id%}">删除</a></button>   
            </div>

            <div class="col-md-2 col-xs-2">
              <button type="button" class="btn btn-default"><a href="{% url 'working_logs:review' project.id%}">审查</a></button>   
            </div>

          </div>            
        </div>
  {% empty %}
    <li>还没有项目被添加</li>
  {% endfor %}
</ul>
    
    <h4><a href="{% url 'working_logs:new_project' %}">Add a new project</a></h4>


  <nav aria-label="Page navigation">
    <ul class="pagination">
      {% if page.has_previous %}
          <li>
            <a href="{% url 'working_logs:results' projects_name page.previous_page_number %}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
      {% endif %}

      {% for num in page.paginator.page_range %}
          {% if num == page.number %}
            <li class='active'><a href="#">{{num}}</a></li>
          {% else %}
            <li><a href="{% url 'working_logs:results' projects_name num %}">{{num}}</a></li>
          {% endif %}
      {% endfor %}

      {% if page.has_next %}
          <li>
            <a href="{% url 'working_logs:results' projects_name page.next_page_number %}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
      {% endif %}
    </ul>
  </nav>
  {% endblock content %}

working_logs/templates/working_logs/review.html
{% extends "working_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2><a href="{% url 'working_logs:project' project.id %}">项目审查</a></h2>
{% endblock header %}

{% block content %}
<head>{{form.media}}</head>   
    <form action="{% url 'working_logs:review' project.id %}" method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button name="submit" class="btn btn-primary">确认</button>
        {% endbuttons %}
    </form>

{% endblock content %}